### ISSUE TITLE
[GENERAL] Package takeover

### ISSUE THREAD

**Issue by vivi90** [atom-extensions/dec-hex-oct-bin#5]
@erkkikeranen 
Hello, Erkki Keränen.
I want to take over your package to fix, maintain and improve it.

With best regards, 
Vivien Richter

**Comment by erkkikeranen** [comment]
Hi @vivi90 ,
Thanks for your interest!

I’d be glad if you would like to do it. How would you like to  proceed?

**Comment by vivi90** [comment]
@erkkikeranen I see there three possible ways:
 * Transfer the repository directly to me.
 * Create a new organization, transfer the repository there. Create a team with admin rights over this repository in this organization and add me to this team.
 * Move the repository to an existing similar organization: https://github.com/atom-extensions

**Comment by vivi90** [comment]
@erkkikeranen Asked my team members. Waiting for the answer. :-)

**Comment by erkkikeranen** [comment]
Hi, I'll transfer over the repository to your organization. 

I'm glad if you want to continue work on the project. 

I would be glad if you mention me as the original author (Erkki Keränen) in the Readme, as a footnote :)

I have no particular interest in maintaining the organization, so I would prefer transfering the repo either to you or the atom-extensions organization (latter preferred?)

**Comment by vivi90** [comment]
@erkkikeranen Of course you will be mentioned :slightly_smiling_face: 
I am currently waiting for the okay of our organization owner.
So if you don't want to wait, it's okay to transfer it to me and i will later transfer it to the organization.

**Comment by vivi90** [comment]
@erkkikeranen Okay, i have the okay of all my team members. Ready to take off :smile: 
So please transfer it to: https://github.com/atom-extensions

**Comment by vivi90** [comment]
@erkkikeranen We need also your API token from https://atom.io/account to be able to publish updates.

**Comment by erkkikeranen** [comment]
I'm currently a few days away from my computer, so I'll do it on thursday. Can you provide an e-mail adress or other mean to deliver api token?

**Comment by vivi90** [comment]
@erkkikeranen Okay, no Problem :-) Yes, i will until thursday.

**Comment by vivi90** [comment]
@erkkikeranen I see we don't really need the API token, if you transfer the whole repository to our organization.
So just transfer it to https://github.com/atom-extensions and everything is fine. :slightly_smiling_face:

**Comment by erkkikeranen** [comment]
I guess I need to transfer it to your personal account because I don't have write access to your organization

**Comment by vivi90** [comment]
@erkkikeranen Just moved :slightly_smiling_face: 
Thank you very much!

**Comment by sdinesh86** [comment]
@erkkikeranen thanks 👍 and @vivi90 also for taking the time for it

**Comment by vivi90** [comment]
@sdinesh86 Might you please adjust the team permissions for this repository, so we are able to rollout some fixes?

**Comment by sdinesh86** [comment]
I have set Maintainers role to our group

**Comment by vivi90** [comment]
@sdinesh86 As long as the ATOM_ACCESS_TOKEN is also authorized for use in this repository, it should be fine. :slightly_smiling_face:

**Comment by vivi90** [comment]
@UziTech This package still needs a build process :-) Also maybe a switch-over to JavaScript?

**Comment by UziTech** [comment]
I'm currently stretched pretty thin. It might take me a couple weeks to get to that but it is on my todo list.

**Comment by vivi90** [comment]
@UziTech Okay, no problem :-)

**Comment by vivi90** [comment]
@UziTech @sdinesh86 @erkkikeranen I think, it's time to close this issue now :tada: 
Now i will starting with refactoring and rewriting the code.
@erkkikeranen Please don't hestitate to open an issue, if there is something you want to say. :slightly_smiling_face:
