### ISSUE TITLE
[REFACTORING] Complete rewriting

### ISSUE THREAD

**Issue by vivi90** [atom-extensions/dec-hex-oct-bin#6]
The code needs to be completely rewritten, because it's too old.

**Comment by vivi90** [comment]
@UziTech I have started rewriting it, but i am not able to get it working.
Something with the serialization might be wrong but i have no idea, how to solve it, so i am not able to continue.
So i have pushed it to: https://github.com/atom-extensions/dec-hex-oct-bin/tree/WIP-6

**Comment by UziTech** [comment]
Whenever I have moved from coffeescript to js I use https://decaffeinate-project.org/repl/ to translate it then clean up the code.

**Comment by UziTech** [comment]
This seems to work as is. What exactly isn't working?

**Comment by UziTech** [comment]
I see. it looks like the issue is you are not saving the view to `this.view` when deserializing

I fixed it in https://github.com/atom-extensions/dec-hex-oct-bin/commit/7ff83d7886229535364bb1f3cbe746283895bcf2

**Comment by vivi90** [comment]
@UziTech In https://github.com/atom-extensions/atom-music/blob/master/lib/atom-music.js it's also not saved to `this.atomMusicView`, when it deserializes. So i don't understand the issue.
Nevertheless, thank you very much! :slightly_smiling_face: 
I will test it later.

**Comment by UziTech** [comment]
hmm that is strange. I'm not sure why that works.

**Comment by UziTech** [comment]
It looks like serialization wasn't working in atom-music. https://github.com/atom-extensions/atom-music/pull/36 should fix it

**Comment by vivi90** [comment]
@UziTech No, serialization works, because the playlist doesn't appears. At least in my Atom.

**Comment by UziTech** [comment]
when you refresh atom the playlist stays?

**Comment by vivi90** [comment]
@UziTech What do you mean with 'refresh'?

**Comment by UziTech** [comment]
I meant reload Atom. If you open atom music in the bottom dock then close atom, the next time you open atom atom-music should be opened in the bottom dock without needing to "toggle" it.

**Comment by vivi90** [comment]
@UziTech Oh yes, your right. It needs to be "toggled".

**Comment by UziTech** [comment]
serialization is for Atom to save the state across reloads and automatically resume the view when Atom starts. With my PR https://github.com/atom-extensions/atom-music/pull/36 it should be working for atom-music

**Comment by vivi90** [comment]
@UziTech Yes, i know. But why it resumes the content of the view (the playlist) successfully, also if the serialization is broken?
(Just try to understand Atom in a better way, because the manual is not so great.)
Yes, i will check your PR soon.
